#!/bin/bash

# prepare local filesystem requirements
echo `hostname` > ~/misc/hostname.log
mkdir ~/misc

# kill other docker containers
docker stop $(docker ps -aq -f "name=horovodcustomngrok") && docker rm $(docker ps -aq -f "name=horovodcustomngrok")

# start container
docker run --runtime=nvidia -it \
--gpus all \
--privileged \
-v ~/bin:/root/bin \
-v ~/ckpt:/root/ckpt \
-v ~/datasets:/root/datasets \
-v ~/repo:/root/repo \
-v ~/misc:/root/misc \
-v /datasets:/root/datasets_root \
-d \
--shm-size 56G \
--name jupyter \
wrhuang/default:horovodcustom bash > ~/misc/containerId.log

#sleep 2
# run command inside container to start ssh server
docker exec -d `cat ~/misc/containerId.log` sh -c /root/nssh
docker exec -d `cat ~/misc/containerId.log` sh -c /root/nssh

# print port
sleep 4
cat ~/misc/ngrokport.log
