#!/bin/bash

echo `hostname` > ~/misc/hostname.log
mkdir ~/misc

docker stop $(docker ps -aq) && docker rm $(docker ps -aq)

docker pull wrhuang/default

docker run --runtime=nvidia -it \
-v ~/bin:/root/bin \
-v ~/ckpt:/root/ckpt \
-v ~/datasets:/root/datasets \
-v ~/repo:/root/repo \
-v ~/misc:/root/misc \
-d \
wrhuang/default bash > ~/misc/containerId.log

cat ~/misc/ngrokport.log
