#!/bin/bash

# prepare local filesystem requirements
echo `hostname` > ~/misc/hostname.log
mkdir ~/misc

# kill other docker containers
docker stop $(docker ps -aq -f "name=dont_kill_guest") && docker rm $(docker ps -aq -f "name=dont_kill_guest")

# start container
docker run --runtime=nvidia -it \
-v ~/bin:/root/bin \
-v ~/ckpt:/root/ckpt \
-v ~/datasets:/root/datasets \
-v ~/misc:/root/misc \
-d \
--shm-size 56G \
--name dont_kill_guest \
wrhuang/default bash > ~/misc/containerId.log

#sleep 2
# run command inside container to start ssh server
docker exec -d `cat ~/misc/containerId.log` sh -c /root/nsshguest
docker exec -d `cat ~/misc/containerId.log` sh -c /root/nsshguest

# print port
sleep 4
cat ~/misc/ngrokport.log
