FROM wrhuang/base

RUN pip install opencv-python
RUN apt-get install openssh-server && apt-get clean
RUN apt-get install x11-server-utils && apt-get clean
RUN pip install editdistance
RUN git clone https://github.com/wronnyhuang/bin
RUN echo nssh >> ~/.bashrc

WORKDIR "/root"
CMD ["nssh"]
