#!/bin/bash

# prepare local filesystem requirements
echo `hostname` > ~/misc/hostname.log
mkdir ~/misc

# kill other docker containers
docker stop $(docker ps -aq) && docker rm $(docker ps -aq)

# start container
docker run --runtime=nvidia -it \
-v ~/bin:/root/bin \
-v ~/ckpt:/root/ckpt \
-v ~/datasets:/root/datasets \
-v ~/repo:/root/repo \
-v ~/misc:/root/misc \
-d \
wrhuang/add bash > ~/misc/containerId.log

# run command inside container to start ssh server
containerId=`cat ~/misc/containerId.log`
echo $containerId
docker exec -d $containerId sh -c /root/nssh

# print port
sleep 4
cat ~/misc/ngrokport.log
