#!/bin/bash

# prepare local filesystem requirements
echo `hostname` > ~/misc/hostname.log
mkdir ~/misc

# kill other docker containers
docker stop $(docker ps -aq -f "name=guestdontkill") && docker rm $(docker ps -aq -f "name=guestdontkill")

# start container
docker run --runtime=nvidia -it \
-v ~/bin:/root/bin \
-v ~/datasets:/root/datasets \
-v ~/guest:/root/guest \
-v ~/misc:/root/misc \
-d \
--shm-size 56G \
--name guestdontkill \
wrhuang/default bash > ~/misc/containerIdGuest.log

#sleep 2
# run command inside container to start ssh server
docker exec -d `cat ~/misc/containerIdGuest.log` sh -c /root/nsshguest
docker exec -d `cat ~/misc/containerIdGuest.log` sh -c /root/nsshguest

# print port
sleep 4
cat ~/misc/ngrokport_guest.log
