:noremap J 5j
:noremap K 5k
:noremap U <c-r>
:noremap , gT
:noremap . gt
:noremap t .
:noremap ] ;
:noremap [ ,
:noremap ; <c-u>
:noremap ' <c-d>
:noremap H ^
:noremap L $
:noremap Y y$
:noremap M `
:noremap <Space>; ?^class<CR>
:noremap <Space>' /^class<CR>
:noremap g; ?def<CR>
:noremap g' /def<CR>
:noremap <A-v> <C-v>

