#!/bin/bash
pkill -f ngrok
service ssh restart
sleep 1

# index=$1
# hname=`hostname`
hname=`cat /root/misc/hostname.log`
echo $hname
if [ "$hname" = "max" ]; then
  $HOME/ngrok authtoken 5S28rBKgc22ZW7evyedNT_YvEm15RZSHdXgS4QwYbk
elif [ "$hname" = "tricky" ]; then
  $HOME/ngrok authtoken 46BUGD4XhUPTaHq7XJBwv_7e1PZUn5Qm6Z2735i64UN
elif [ "$hname" = "tomg3264" ]; then
  $HOME/ngrok authtoken 81CyUW18RB5tJ1RWi67MY_7onRym1VRC82KWB9pqTLs
elif [ "$hname" = "deeplearner2" ]; then
  $HOME/ngrok authtoken 6qrCQcwWbKiUo94JMUkKs_26cSZzqzgkREzx8y7cmUU
else
	echo invalid hostname given!! update nssh script
fi

nohup $HOME/ngrok tcp 22 &
sleep 1
curl -s http://localhost:4040/api/tunnels | python3 -c \
	"import sys, json; address = json.load(sys.stdin)['tunnels'][0]['public_url']; open('/root/misc/ngrokport.log','w+').write('`date` $hname: '+address); print(address)"
