#!/bin/bash
service ssh restart
pkill -f ngrok
nohup ngrok tcp 22 &
sleep 1
curl -s http://localhost:4040/api/tunnels | python3 -c \
  "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"
