#alias la='ls -latsh'
#alias ag="g=$(p4 --format '%clientRoot%' info)/google3"
alias gpaste="/google/src/head/depot/eng/tools/pastebin"
#alias gengbash="/google/src/head/depot/google3/util/shell/gbash/tools/gen_gbash.sh"
alias tensorboard="/google/src/head/depot/google3/learning/brain/tensorboard/tensorboard.sh --port=6007 --logdir"
alias fu="fileutil"
alias analog=". /e/scripts/analog.sh"
#alias ae="e=$(p4 --format '%clientRoot%' info)/google3/experimental/users/wrh"
alias sync2adhoc="sh /head/learning/brain/research/babelfish/speech/params/soda_ad_hoc/sync_to_mpm_cl.sh"
alias synccl="p4 --format '%SyncChange%' client -o"
alias tmux="tmx2"
alias "bgrep=/google/data/ro/teams/borgtools/bgrep -u wrh,speech-modeling-e2e-ready-jobs"
alias "bkill=/google/data/ro/teams/borgtools/bkill -u wrh,speech-modeling-e2e-ready-jobs"
alias "btail=/google/data/ro/teams/borgtools/btail -u wrh,speech-modeling-e2e-ready-jobs"
#alias bkick="bgrep --restart"
